version: '3.2'

services:
  base-service:
    iamge: hero-base-service
    depends_on:
      - hero-service
      - config
      - eureka
    ports:
      - 8090:8090
  hero-service:
    image: hero-hero-service
    ports:
      - 8083:8083
    depends_on:
      - config
      - eureka
      - db
  battlegrounds-service:
    image: hero-battlegrounds-service
    depends_on:
      - eureka
      - config
    ports:
      - 8094:8094
  getaway:
    image: hero-getaway
    ports:
      - 8080:8080
    depends_on:
      - config
      - eureka
      - redis
  eureka:
    image: hero-eureka-service
    ports:
      - 8766:8766
    depends_on:
      - config
  config:
    image: hero-configuration-service
    ports:
      - 7666:7666
  db:
    image: mongo:3.7.1-jessie
    volumes:
      - "dbdata:/data/db"
  redis:
    image: redis:3.2.11

volumes:
  dbdata: