version: '3.2'

services:
  web:
    image: base-microservice
    build: ./base-service
    depends_on:
      - data
      - config
      - eureka
    ports:
      - 8090:8090
  data:
    build: ./dataprovider-service
    ports:
      - 8083:8083
    depends_on:
      - config
      - eureka
      - db
  getaway:
    build: ./getaway
    ports:
      - 8080:8080
    depends_on:
      - config
      - eureka
  eureka:
    build: ./eureka-service
    ports:
      - 8766:8766
    depends_on:
      - config
  config:
    build: ./configuration-service
    ports:
      - 7666:7666
  db:
    image: mongo:3.7.1-jessie
    volumes:
      - "dbdata:/data/db"

volumes:
  dbdata: