version: '3.2'

services:
  base-service:
    image: base-microservice
    build: ./base-service
    depends_on:
      - hero-service
      - config
      - eureka
    ports:
      - 8090:8090
  hero-service:
    build: ./hero-service
    ports:
      - 8083:8083
    depends_on:
      - config
      - eureka
      - db
  battlegrounds-service:
    build: ./battlegrounds-service
    depends_on:
      - eureka
      - config
    ports:
      - 8094:8094
  getaway:
    build: ./getaway
    ports:
      - 8080:8080
    depends_on:
      - config
      - eureka
  eureka:
    build: ./eureka-service
    ports:
      - 8766:8766
    depends_on:
      - config
  config:
    build: ./configuration-service
    ports:
      - 7666:7666
  db:
    image: mongo:3.7.1-jessie
    volumes:
      - "dbdata:/data/db"

volumes:
  dbdata: