version: '2.3'

services:
  base-service:
    image: hero-base-service
    depends_on:
      hero-service:
        condition: service_healthy
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - 8090:8090

  hero-service:
    image: hero-hero-service
    ports:
      - 8083:8083
    depends_on:
      config:
         condition: service_healthy
      eureka:
         condition: service_healthy
      mongodb:
         condition: service_healthy

  battlegrounds-service:
    image: hero-battlegrounds-service
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    ports:
      - 8094:8094

  user-service:
    image: user-service
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - 8095:8095

  getaway:
    image: hero-getaway
    ports:
      - 8080:8080
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy

  eureka:
    image: hero-eureka-service
    ports:
      - 8766:8766
    depends_on:
      config:
        condition: service_healthy

  config:
    image: hero-configuration-service
    ports:
      - 7666:7666

  mongodb:
    image: mongo:3.7.1-jessie
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - ~/heroes/mongo/storage:/data/db

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_storage
    ports:
      - 3306:3306
    volumes:
      - ~/heroes/mysql/db/store:/var/lib/mysql
