INSERT INTO app_user(ID, USERNAME, PASSWORD) VALUES(1, 'ADMIN', '$2a$10$UIh4n3oAhnZvB6UelYfYPecsWnGiNym0Yqn7j.A5hzdp044pJUYT.');
INSERT INTO user_role(APP_USER_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO user_role(APP_USER_ID, ROLE) VALUES (1, 'MEMBER');